prefeito:
  - prefeito
  - prefeita
  - gabinete do prefeito
  - gabinete da prefeita
  - chefe do executivo

vice_prefeito:
  - vice-prefeito
  - vice prefeito
  - vice-prefeita
  - vice prefeita

chefe_gabinete:
  - chefe de gabinete
  - chefia de gabinete
  - gabinete

desenvolvimento_economico:
  - desenvolvimento econômico
  - secretaria de desenvolvimento econômico
  - secretaria municipal de desenvolvimento econômico
  - secretário municipal de desenvolvimento econômico
  - indústria e comércio
  - desenvolvimento, indústria e comércio
  - desenvolvimento econômico e turismo
  - trabalho e desenvolvimento econômico

desenvolvimento:
  - secretaria de desenvolvimento
  - secretaria municipal de desenvolvimento
  - secretário municipal de desenvolvimento
  - desenvolvimento
  - desenvolvimento urbano

financas_fazenda:
  - finanças
  - fazenda
  - secretaria de finanças
  - secretaria municipal de finanças
  - secretaria da fazenda
  - secretaria municipal da fazenda
  - secretário municipal de finanças
  - secretário municipal da fazenda
  - administração e finanças
  - finanças e planejamento

planejamento:
  - planejamento
  - planejameto
  - secretaria de planejamento
  - secretaria municipal de planejamento
  - secretaria municipal de planejameto
  - secretário municipal de planejamento
  - planejamento urbano
  - gestão e planejamento
  - planejamento e gestão

agencia_desenvolvimento:
  - agência de desenvolvimento
  - agencia de desenvolvimento
  - desenvolvimento municipal
  - sala do empreendedor
  - banco do povo
  - casa do empreendedor

